import { useState } from 'react';
import type { Case } from '../types';
import { caseNatures } from '../lib/case-utils';
import { Field, PersonFields } from './forms';

export function CaseEditor({item,save,close}:{item:Case;save:(item:Case)=>Promise<void>;close:()=>void}) {
  const [caseItem,setCaseItem]=useState(item); const [errors,setErrors]=useState<Record<string,string>>({});
  const submit=async(event:React.FormEvent)=>{event.preventDefault();const next:Record<string,string>={};(['case_number','nature_of_case','case_description','place_of_incident','date_of_incident','date_of_lupon_hearing'] as const).forEach(key=>{if(!caseItem[key])next[key]='Required.'});(['complainant','respondent'] as const).forEach(role=>{const person=caseItem[role];if(!person.first_name)next[role+'.first_name']='Required.';if(!person.last_name)next[role+'.last_name']='Required.';if(!person.date_of_birth||new Date(person.date_of_birth)>new Date())next[role+'.date_of_birth']='Enter a valid past date.';if(!/^09\d{9}$/.test(person.contact_number))next[role+'.contact_number']='Use an 11-digit number beginning with 09.'});setErrors(next);if(Object.keys(next).length)return;try{await save(caseItem);close();}catch(error){setErrors({form:error instanceof Error?error.message:'Unable to save.'});}};
  const roleErrors=(role:string)=>Object.fromEntries(Object.entries(errors).filter(([key])=>key.startsWith(role+'.')).map(([key,value])=>[key.slice(role.length+1),value]));
  return <div className="modal-backdrop"><form className="modal form" onSubmit={submit}><div className="modal-head"><h2>{caseItem.id?'Edit Case':'New Case'}</h2><button type="button" className="icon-btn" onClick={close}>Ã—</button></div>{errors.form&&<div className="alert">{errors.form}</div>}<section className="form-section"><h3>Case Information</h3><div className="form-grid"><Field label="Case Number" required value={caseItem.case_number} set={value=>setCaseItem({...caseItem,case_number:value})} error={errors.case_number}/><label className="field"><span>Nature of Case *</span><select value={caseItem.nature_of_case} onChange={event=>setCaseItem({...caseItem,nature_of_case:event.target.value})}><option value="">Select nature of case</option>{caseNatures.map(nature=><option key={nature}>{nature}</option>)}</select>{errors.nature_of_case&&<small>{errors.nature_of_case}</small>}</label><label className="field"><span>Case Status *</span><select value={caseItem.status} onChange={event=>setCaseItem({...caseItem,status:event.target.value as Case['status']})}><option>Active</option><option>Settled</option><option>Unsettled</option></select></label><Field label="Place of Incident" required value={caseItem.place_of_incident} set={value=>setCaseItem({...caseItem,place_of_incident:value})}/><Field label="Date of Incident" required type="date" value={caseItem.date_of_incident} set={value=>setCaseItem({...caseItem,date_of_incident:value})}/><Field label="Time of Incident" type="time" value={caseItem.time_of_incident} set={value=>setCaseItem({...caseItem,time_of_incident:value})}/><Field label="Date of Lupon Hearing" required type="date" value={caseItem.date_of_lupon_hearing} set={value=>setCaseItem({...caseItem,date_of_lupon_hearing:value})}/></div><label className="field full"><span>Case Description *</span><textarea value={caseItem.case_description} onChange={event=>setCaseItem({...caseItem,case_description:event.target.value})}/></label></section><PersonFields title="Complainant Information" value={caseItem.complainant} set={person=>setCaseItem({...caseItem,complainant:person})} errors={roleErrors('complainant')}/><PersonFields title="Respondent Information" value={caseItem.respondent} set={person=>setCaseItem({...caseItem,respondent:person})} errors={roleErrors('respondent')}/><div className="actions end"><button type="button" className="secondary" onClick={close}>Cancel</button><button>Save Case</button></div></form></div>;
}
