import { useEffect, useMemo, useState } from 'react';
import { BarChart3, FolderArchive, LayoutDashboard, LogOut, Plus, Settings, Users } from 'lucide-react';
import type { Case } from './types';
import { store } from './lib/storage';
import { blankCase, matchesCaseSearch, tableColumns } from './lib/case-utils';
import { CaseEditor } from './components/CaseEditor'; import { Logo } from './components/common';
import { Login } from './pages/Login'; import { Dashboard } from './pages/Dashboard'; import { Cases } from './pages/Cases'; import { Residents } from './pages/Residents'; import { Reports } from './pages/Reports'; import { SettingsPage } from './pages/Settings';
import './styles.css';
export default function App(){const[auth,setAuth]=useState(sessionStorage.getItem('bf-auth')==='yes'),[page,setPage]=useState('Dashboard'),[cases,setCases]=useState<Case[]>([]),[edit,setEdit]=useState<Case|null>(null),[query,setQuery]=useState(''),[visibleColumns,setVisibleColumns]=useState(()=>tableColumns.map(column=>column.id)),[columnsOpen,setColumnsOpen]=useState(false),[note,setNote]=useState(''),[darkMode,setDarkMode]=useState(localStorage.getItem('bf-dark-theme')==='on');const load=()=>store.cases().then(setCases);useEffect(()=>{load();},[]);const refreshForAuthChange=()=>window.location.reload();const save=async(item:Case)=>{await store.saveCase(item);load();setNote('Case record saved successfully.');};const del=async(id:number)=>{if(confirm('Delete this case record?')){await store.deleteCase(id);load();}};const filtered=useMemo(()=>cases.filter(item=>matchesCaseSearch(item,query)),[cases,query]);if(!auth)return <Login ok={()=>{sessionStorage.setItem('bf-auth','yes');setAuth(true);refreshForAuthChange();}}/>;const body=page==='Dashboard'?<Dashboard cases={cases}/>:page==='Cases'?<Cases query={query} setQuery={setQuery} data={filtered} edit={setEdit} del={del} visibleColumns={visibleColumns} setVisibleColumns={setVisibleColumns} columnsOpen={columnsOpen} setColumnsOpen={setColumnsOpen} add={()=>setEdit(blankCase())}/>:page==='Residents'?<Residents/>:page==='Reports'?<Reports cases={cases}/>:<SettingsPage note={setNote} darkMode={darkMode} setDarkMode={setDarkMode}/>;const navigation=[['Dashboard',LayoutDashboard],['Residents',Users],['Cases',FolderArchive],['Reports',BarChart3],['Settings',Settings]] as const;return <div className={`app ${darkMode?'dark-mode':''}`}><aside><div className="brand"><Logo small/><span>Barangay Flores<small>Case Management</small></span></div><nav>{navigation.map(([label,Icon])=><button key={label} className={page===label?'active':''} onClick={()=>setPage(label)}><Icon size={19}/>{label}</button>)}</nav><button className="logout" onClick={()=>{sessionStorage.clear();setAuth(false);refreshForAuthChange();}}><LogOut size={18}/> Sign out</button></aside><main className="content"><header><div><p className="crumb">Home / {page}</p><h1>{page}</h1></div>{page==='Dashboard'&&<button onClick={()=>setEdit(blankCase())}><Plus size={17}/> New Case</button>}</header>{note&&<div className="notice">{note}</div>}{body}</main>{edit&&<CaseEditor item={edit} save={save} close={()=>setEdit(null)}/>}</div>;}
